// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace World
{

using global::System;
using global::FlatBuffers;

public partial struct Cell : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Cell GetRootAsCell(ByteBuffer _bb) { return GetRootAsCell(_bb, new Cell()); }
  public static Cell GetRootAsCell(ByteBuffer _bb, Cell obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Cell __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public TileMap? TileMaps(int j) { int o = __p.__offset(4); return o != 0 ? (TileMap?)(new TileMap()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int TileMapsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Cell> CreateCell(FlatBufferBuilder builder,
      VectorOffset tileMapsOffset = default(VectorOffset)) {
    builder.StartObject(1);
    Cell.AddTileMaps(builder, tileMapsOffset);
    return Cell.EndCell(builder);
  }

  public static void StartCell(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddTileMaps(FlatBufferBuilder builder, VectorOffset tileMapsOffset) { builder.AddOffset(0, tileMapsOffset.Value, 0); }
  public static VectorOffset CreateTileMapsVector(FlatBufferBuilder builder, Offset<TileMap>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateTileMapsVectorBlock(FlatBufferBuilder builder, Offset<TileMap>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartTileMapsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Cell> EndCell(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Cell>(o);
  }
};


}
