// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace World
{

public enum ColliderType : sbyte
{
 None = 0,
 Sprite = 1,
 Grid = 2,
};


}
