// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace World
{

using global::System;
using global::FlatBuffers;

public struct Color : IFlatbufferObject
{
  private Struct __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Color __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float Red { get { return __p.bb.GetFloat(__p.bb_pos + 0); } }
  public float Blue { get { return __p.bb.GetFloat(__p.bb_pos + 4); } }
  public float Green { get { return __p.bb.GetFloat(__p.bb_pos + 8); } }
  public float Alpha { get { return __p.bb.GetFloat(__p.bb_pos + 12); } }

  public static Offset<Color> CreateColor(FlatBufferBuilder builder, float Red, float Blue, float Green, float Alpha) {
    builder.Prep(4, 16);
    builder.PutFloat(Alpha);
    builder.PutFloat(Green);
    builder.PutFloat(Blue);
    builder.PutFloat(Red);
    return new Offset<Color>(builder.Offset);
  }
};


}
