// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace World
{

public enum Flag : sbyte
{
 None = 0,
 LockColor = 1,
 LockTransform = 2,
 InstantiateGameObjectRuntimeOnly = 4,
};


}
